const TRANSACTION_POOL_KEY = 'transactionPool';

const HERMEZ_ACCOUNT_ACCESS_MESSAGE =
    'Hermez Network account access.\n\nSign this message if you are in a trusted application only.';

const CREATE_ACCOUNT_AUTH_MESSAGE = 'Account creation';
const EIP_712_VERSION = '1';
const EIP_712_PROVIDER = 'Hermez Network';

const ETHER_TOKEN_ID = 0;

const GAS_LIMIT_HIGH = 170000;
const GAS_LIMIT_LOW = 150000;
const GAS_STANDARD_ETH_TX = 21000;
const GAS_STANDARD_ERC20_TX = 90000;
const GAS_STANDARD_ERC20_TX_OFFSET = 15000;
const GAS_LIMIT_APPROVE_DEFAULT = 45000;
const GAS_LIMIT_APPROVE_OFFSET = 5000;
const GAS_LIMIT_DEPOSIT_OFFSET = 5000;
const GAS_LIMIT_OFFSET = 50000;
const GAS_LIMIT_WITHDRAW_DEFAULT = 230000;
const GAS_LIMIT_WITHDRAW_SIBLING = 31000;
const GAS_LIMIT_WITHDRAW_ERC20_TX = 30000;
const GAS_LIMIT = 5000000;
const GAS_MULTIPLIER = 1;

const DEFAULT_PAGE_SIZE = 20;

const API_VERSION = 'v1';

const INTERNAL_ACCOUNT_ETH_ADDR =
    'hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF';

const STORAGE_VERSION_KEY = 'hermezStorageVersion';
const STORAGE_VERSION = 1;
